name: CI

on:
  push:
    branches:
      - "*"
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build plugin
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/heads')
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Build binary
        run: make

  release:
    name: Release plugin
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Build release
        run: make push

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*
